import { PropertyRole } from '@/common/enums/role.enum';

export const Permissions = {
  PROPERTIES_CREATE: 'properties:create',
  PROPERTIES_LIST: 'properties:list',
  PROPERTIES_UPDATE: 'properties:update',
  PROPERTY_ADMINS_CREATE: 'properties:admins:create',
  PROPERTY_STAFF_CREATE: 'properties:staff:create',
  PROPERTY_USERS_READ: 'properties:users:read',
  ROOM_TYPES_CREATE: 'room-types:create',
  ROOM_TYPES_READ: 'room-types:read',
  ROOM_TYPES_UPDATE: 'room-types:update',
  ROOM_TYPES_DELETE: 'room-types:delete',
  ROOMS_CREATE: 'rooms:create',
  ROOMS_READ: 'rooms:read',
  ROOMS_UPDATE: 'rooms:update',
  ROOMS_DELETE: 'rooms:delete',
  ROOM_BLOCKS_CREATE: 'room-blocks:create',
  ROOM_BLOCKS_READ: 'room-blocks:read',
  ROOM_BLOCKS_UPDATE: 'room-blocks:update',
  ROOM_BLOCKS_DELETE: 'room-blocks:delete',
  RATES_CREATE: 'rates:create',
  RATES_READ: 'rates:read',
  RATES_UPDATE: 'rates:update',
  RATES_DELETE: 'rates:delete',
  AVAILABILITY_READ: 'availability:read',
  BOOKINGS_HOLD: 'bookings:hold',
  BOOKINGS_CONFIRM: 'bookings:confirm',
  BOOKINGS_READ: 'bookings:read',
  BOOKINGS_CANCEL: 'bookings:cancel',
  BOOKINGS_CHECKIN: 'bookings:checkin',
  BOOKINGS_CHECKOUT: 'bookings:checkout',
  PAYMENTS_CREATE: 'payments:create',
  PAYMENTS_REFUND: 'payments:refund',
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];

export const RolePermissions: Record<PropertyRole, Permission[]> = {
  [PropertyRole.SUPER_ADMIN]: [
    Permissions.PROPERTIES_CREATE,
    Permissions.PROPERTIES_LIST,
    Permissions.PROPERTIES_UPDATE,
    Permissions.PROPERTY_ADMINS_CREATE,
    Permissions.PROPERTY_STAFF_CREATE,
    Permissions.PROPERTY_USERS_READ,
    Permissions.ROOM_TYPES_CREATE,
    Permissions.ROOM_TYPES_READ,
    Permissions.ROOM_TYPES_UPDATE,
    Permissions.ROOM_TYPES_DELETE,
    Permissions.ROOMS_CREATE,
    Permissions.ROOMS_READ,
    Permissions.ROOMS_UPDATE,
    Permissions.ROOMS_DELETE,
    Permissions.ROOM_BLOCKS_CREATE,
    Permissions.ROOM_BLOCKS_READ,
    Permissions.ROOM_BLOCKS_UPDATE,
    Permissions.ROOM_BLOCKS_DELETE,
    Permissions.RATES_CREATE,
    Permissions.RATES_READ,
    Permissions.RATES_UPDATE,
    Permissions.RATES_DELETE,
    Permissions.AVAILABILITY_READ,
    Permissions.BOOKINGS_HOLD,
    Permissions.BOOKINGS_CONFIRM,
    Permissions.BOOKINGS_READ,
    Permissions.BOOKINGS_CANCEL,
    Permissions.BOOKINGS_CHECKIN,
    Permissions.BOOKINGS_CHECKOUT,
    Permissions.PAYMENTS_CREATE,
    Permissions.PAYMENTS_REFUND,
  ],
  [PropertyRole.PROPERTY_ADMIN]: [
    Permissions.PROPERTIES_CREATE,
    Permissions.PROPERTIES_LIST,
    Permissions.PROPERTIES_UPDATE,
    Permissions.PROPERTY_STAFF_CREATE,
    Permissions.PROPERTY_USERS_READ,
    Permissions.ROOM_TYPES_CREATE,
    Permissions.ROOM_TYPES_READ,
    Permissions.ROOM_TYPES_UPDATE,
    Permissions.ROOM_TYPES_DELETE,
    Permissions.ROOMS_CREATE,
    Permissions.ROOMS_READ,
    Permissions.ROOMS_UPDATE,
    Permissions.ROOMS_DELETE,
    Permissions.ROOM_BLOCKS_CREATE,
    Permissions.ROOM_BLOCKS_READ,
    Permissions.ROOM_BLOCKS_UPDATE,
    Permissions.ROOM_BLOCKS_DELETE,
    Permissions.RATES_CREATE,
    Permissions.RATES_READ,
    Permissions.RATES_UPDATE,
    Permissions.RATES_DELETE,
    Permissions.AVAILABILITY_READ,
    Permissions.BOOKINGS_HOLD,
    Permissions.BOOKINGS_CONFIRM,
    Permissions.BOOKINGS_READ,
    Permissions.BOOKINGS_CANCEL,
    Permissions.BOOKINGS_CHECKIN,
    Permissions.BOOKINGS_CHECKOUT,
    Permissions.PAYMENTS_CREATE,
    Permissions.PAYMENTS_REFUND,
  ],
  [PropertyRole.PROPERTY_STAFF]: [
    Permissions.ROOM_TYPES_READ,
    Permissions.ROOMS_READ,
    Permissions.ROOM_BLOCKS_READ,
    Permissions.RATES_READ,
    Permissions.AVAILABILITY_READ,
    Permissions.BOOKINGS_HOLD,
    Permissions.BOOKINGS_READ,
    Permissions.BOOKINGS_CHECKIN,
    Permissions.BOOKINGS_CHECKOUT,
    Permissions.PAYMENTS_CREATE,
  ],
};
