export enum BookingSource {
  ONLINE = 'ONLINE',
  WALKIN = 'WALKIN',
  OTA = 'OTA',
  RESERVATION = 'RESERVATION',
}

export enum BookingStatus {
  HOLD = 'HOLD',
  RESERVED = 'RESERVED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  NO_SHOW = 'NO_SHOW',
}
