export enum StayStatus {
  ACTIVE = 'ACTIVE',
  CHECKED_OUT = 'CHECKED_OUT',
  EARLY_CHECKOUT = 'EARLY_CHECKOUT',
  EXTENDED = 'EXTENDED',
  ROOM_CHANGED = 'ROOM_CHANGED',
  UPGRADED = 'UPGRADED',
  CANCELLED = 'CANCELLED',
}

export enum StayLogAction {
  CHECK_IN = 'CHECK_IN',
  ROOM_CHANGE = 'ROOM_CHANGE',
  EXTENSION = 'EXTENSION',
  EARLY_CHECKOUT = 'EARLY_CHECKOUT',
  PAYMENT_ADDED = 'PAYMENT_ADDED',
  GUEST_ADDED = 'GUEST_ADDED',
  UPGRADE = 'UPGRADE',
}
